<?php
return [
    'main_db'=>'live_api',
    'client_email'=>'suzen-noreply@suzen.school',
    'student_email_domain' => "@jskl.edu.my",
    'cache_time'=>"24",
    'cache_academic_years'=>"academic_years_",
    'cache_departments'=>"departments_",
    'cache_classes'=>"classes_",    
    'cache_sections'=>"sections_",
    'cache_students' => "students_",
    'cache_parentDetails' => "parentDetails_",
    'cache_Staff' => "Staff_",
    'cache_timetable' => "cache_timetable_",
    'cache_leaveTypeWiseAllReason' => "cache_leaveTypeWiseAllReason_",
    'cache_ReasonsByLeaveType' => "cache_ReasonsByLeaveType_",
    'cache_semester' => "cache_semester_",
    'cache_eventDetails' => "cache_eventDetails_", 
    'cache_student_leave_types' => "student_leave_types_",
    'cache_subjects' => "subjects_",
    'cache_exam_papers' => "exam_papers_",
    'cache_exam_term' => "exam_term_",
    'cache_exam' => "exam_",
    'cache_educations' => "educations_",
    'cache_religions' => "religions_",
    'cache_race' => "race_",
    'cache_absent_reasons' => "absent_reasons_",
    'cache_late_reasons' => "late_reasons_",
    'cache_excused_reasons' => "excused_reasons_", 
    'cache_holidays' => "holidays_", 
    'cache_leave_types' => "leave_types_",
    'cache_get_access_menu_list' => "cache_get_access_menu_list_",
    'school_role_access' => "school_role_access_",
    'cache_teacher_students' => "cache_teacher_students",
    
];
